# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

alternating_debiased_sparse_pca <- function(X, beta_hat, lambda, T, max_iter = 100L, tol = 1e-6) {
    .Call(`_SA24204138_alternating_debiased_sparse_pca`, X, beta_hat, lambda, T, max_iter, tol)
}

